export const MENU_SCHEMA = {
  type: 'object',
  properties: {
    pid: {
      type: 'string',
      title: '父级',
      required: true,
      // 'x-hidden': '{{showPid}}',
      enum:[{}],
      'x-decorator': 'FormItem',
      'x-component': 'TreeSelect',
      'x-read-pretty': true,
      'x-reactions': '{{fetchMenuTree}}',
    },
    type: {
      type: 'string',
      title: '类型',
      required: false,
      enum:  [
        { label: '目录', value: 1 },
        { label: '菜单', value: 2 },
        { label: '按钮', value: 3 },
      ],
      'x-decorator': 'FormItem',
      'x-component': 'Select',
      'x-read-pretty': '{{readOnly}}',
      'x-component-props': {
        placeholder: '请选择类型',
      },
    },
    name: {
      type: 'string',
      title: '名称',
      required: true,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input',
      'x-validator': [
        {
          triggerType: 'onBlur',
          max: 100,
          min: 1,
          required: true,
          whitespace: true,
          message: '名称应在1-100个字符之间',
        },
      ],
      'x-component-props': {
        placeholder: '请输入名称',
        allowClear: true,
        maxLength: 100,
      },
    },
    routePath: {
      type: 'string',
      title: '路由地址',
      required: false,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input',
      'x-component-props': {
        placeholder: '请输入路由地址',
        allowClear: true,
        maxLength: 100,
      },
    },
    pagePath: {
      type: 'string',
      title: '组件地址',
      required: false,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input',
      'x-component-props': {
        placeholder: '请输入组件地址',
        allowClear: true,
        maxLength: 100,
      },
    },
    icon: {
      type: 'string',
      title: '图标',
      required: false,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'SelectIcon',
      'x-component-props': {
        placeholder: '请选择图标',
      },
    },
    permissionCode: {
      type: 'string',
      title: '权限',
      required: true,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input',
      'x-validator': [
        {
          triggerType: 'onBlur',
          max: 100,
          min: 1,
          required: true,
          whitespace: true,
          message: '权限应在1-100个字符之间',
        },
      ],
      'x-component-props': {
        placeholder: '请输入权限',
        allowClear: true,
        maxLength: 100,
      },
    },
    includePermissionCode: {
      type: 'string',
      title: '附加权限',
      required: false,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input.TextArea',
      'x-component-props': {
        placeholder: '请输入附加权限',
        allowClear: true,
        maxLength: 2000,
      },
    },
    remark: {
      type: 'string',
      title: '描述信息',
      required: false,
      'x-decorator': 'FormItem',
      'x-read-pretty': '{{readOnly}}',
      'x-component': 'Input.TextArea',
      'x-component-props': {
        placeholder: '请输入描述信息',
        allowClear: true,
        maxLength: 2000,
      },
    },
    sort: {
      type: 'number',
      title: '排序',
      required: true,
      'x-decorator': 'FormItem',
      'x-component': 'NumberPicker',
      'x-read-pretty': '{{readOnly}}',
      'x-validator': [
        {
          triggerType: 'onBlur',
          required: false,
          whitespace: true,
          message: '请输入排序',
        },
      ],
      'x-component-props': {
        placeholder: '请输入排序',
        allowClear: true,
        max: 999999,
        min: 0,
      },
    },
  },
}