import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import './globals.css'
import { ConfigProvider } from 'antd'
import zhCN from 'antd/locale/zh_CN';
import AuthContext from './context/AuthContext'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
    // 
		<html lang="en" data-theme="light">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
          <AuthContext>
					  <AntdRegistry>{children}</AntdRegistry>
          </AuthContext>
			</body>
		</html>
	)
}
